import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingBag,Heart,Star,Plus,Minus,X,Menu as MenuIcon,MapPin,Phone,Clock,ChefHat,ArrowRight,CheckCircle} from 'lucide-react';
import './styles.css';

const menu=[
{id:1,name:'Truffle Mushroom Pizza',cat:'Pizza',price:349,rating:4.9,img:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85',desc:'Wood-fired crust, truffle cream, mushrooms & mozzarella',tag:'Chef Pick'},
{id:2,name:'Smoky BBQ Burger',cat:'Burgers',price:299,rating:4.8,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',desc:'Char-grilled patty, smoky BBQ sauce, cheddar & crispy onions',tag:'Popular'},
{id:3,name:'Creamy Alfredo Pasta',cat:'Pasta',price:279,rating:4.7,img:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',desc:'Silky parmesan sauce, herbs, roasted garlic & penne',tag:'Bestseller'},
{id:4,name:'Butter Chicken Bowl',cat:'Indian',price:329,rating:4.9,img:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=900&q=85',desc:'Creamy tomato butter chicken served with fragrant basmati rice',tag:'Spicy'},
{id:5,name:'Crispy Chicken Tacos',cat:'Mexican',price:259,rating:4.6,img:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=900&q=85',desc:'Crispy chicken, salsa, avocado crema & fresh lime',tag:'New'},
{id:6,name:'Paneer Tikka Platter',cat:'Indian',price:289,rating:4.8,img:'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=900&q=85',desc:'Smoky paneer, peppers, onions and mint chutney',tag:'Veg'},
{id:7,name:'Chocolate Lava Cake',cat:'Desserts',price:199,rating:4.9,img:'https://images.unsplash.com/photo-1606313564200-e75d5e30476a?auto=format&fit=crop&w=900&q=85',desc:'Warm chocolate cake with a molten center and vanilla cream',tag:'Sweet'},
{id:8,name:'Berry Cheesecake',cat:'Desserts',price:219,rating:4.7,img:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=85',desc:'Creamy cheesecake topped with fresh seasonal berries',tag:'Fresh'},
{id:9,name:'Mango Mojito',cat:'Drinks',price:149,rating:4.6,img:'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=900&q=85',desc:'Fresh mango, mint, lime and sparkling soda',tag:'Cool'},
{id:10,name:'Cold Coffee',cat:'Drinks',price:139,rating:4.8,img:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=85',desc:'Chilled coffee, creamy foam and a touch of chocolate',tag:'Chill'},
{id:11,name:'Margherita Pizza',cat:'Pizza',price:249,rating:4.7,img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',desc:'Tomato, basil, mozzarella and extra virgin olive oil',tag:'Classic'},
{id:12,name:'Loaded Fries',cat:'Burgers',price:179,rating:4.5,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',desc:'Golden fries loaded with cheese, jalapeños and sauce',tag:'Snack'}
];
const cats=['All','Pizza','Burgers','Pasta','Indian','Mexican','Desserts','Drinks'];
const money=n=>`₹${n}`;

function App(){
 const [active,setActive]=useState('All'),[query,setQuery]=useState(''),[cart,setCart]=useState([]),[liked,setLiked]=useState([]),[cartOpen,setCartOpen]=useState(false),[mobile,setMobile]=useState(false),[checkout,setCheckout]=useState(false),[ordered,setOrdered]=useState(false);
 const filtered=useMemo(()=>menu.filter(x=>(active==='All'||x.cat===active)&&(x.name.toLowerCase().includes(query.toLowerCase())||x.desc.toLowerCase().includes(query.toLowerCase()))),[active,query]);
 const add=(item)=>setCart(c=>{const found=c.find(x=>x.id===item.id);return found?c.map(x=>x.id===item.id?{...x,qty:x.qty+1}:x):[...c,{...item,qty:1}]});
 const change=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const total=cart.reduce((s,x)=>s+x.price*x.qty,0), count=cart.reduce((s,x)=>s+x.qty,0);
 const toggleLike=id=>setLiked(l=>l.includes(id)?l.filter(x=>x!==id):[...l,id]);
 const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <div>
  <header className="nav"><div className="logo" onClick={()=>scroll('home')}><span>🍽</span> Bella<span className="accent">Bites</span></div><nav className={mobile?'show':''}><button onClick={()=>scroll('home')}>Home</button><button onClick={()=>scroll('menu')}>Menu</button><button onClick={()=>scroll('about')}>About</button><button onClick={()=>scroll('reviews')}>Reviews</button><button onClick={()=>scroll('contact')}>Contact</button></nav><div className="navActions"><button className="iconBtn searchBtn" onClick={()=>document.querySelector('.search input')?.focus()}><Search size={20}/></button><button className="cartBtn" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><b>{count}</b></button><button className="hamb" onClick={()=>setMobile(!mobile)}><MenuIcon/></button></div></header>
  <main>
   <section id="home" className="hero"><div className="heroGlow"></div><div className="heroText"><div className="eyebrow">✦ FRESH • LOCAL • UNFORGETTABLE</div><h1>Good food.<br/><em>Great mood.</em></h1><p>Handcrafted dishes, bold flavors and warm hospitality — made fresh every day at Bella Bites.</p><div className="heroBtns"><button className="primary" onClick={()=>scroll('menu')}>Explore Menu <ArrowRight size={18}/></button><button className="ghost" onClick={()=>scroll('contact')}>Book a Table</button></div><div className="stats"><div><strong>4.9</strong><span>★ Google rating</span></div><div><strong>50+</strong><span>Fresh dishes</span></div><div><strong>20k+</strong><span>Happy guests</span></div></div></div><div className="heroDish"><div className="dishRing"></div><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=90"/><div className="floatCard"><span>🔥</span><div><b>Chef's Special</b><small>Truffle Mushroom Pizza</small></div></div></div></section>
   <section className="marquee"><div>WOOD-FIRED PIZZA ✦ FARM FRESH ✦ CRAFTED WITH LOVE ✦ OPEN DAILY 11 AM — 11 PM ✦ WOOD-FIRED PIZZA ✦ FARM FRESH ✦</div></section>
   <section id="menu" className="section menuSection"><div className="sectionHead"><div><span className="eyebrow">OUR MENU</span><h2>Something for <em>everyone.</em></h2></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search dishes..."/></div></div><div className="cats">{cats.map(c=><button key={c} className={active===c?'active':''} onClick={()=>setActive(c)}>{c}</button>)}</div><div className="grid">{filtered.map(item=><article className="foodCard" key={item.id}><div className="foodImg"><img src={item.img} alt={item.name}/><span>{item.tag}</span><button className={'like '+(liked.includes(item.id)?'liked':'')} onClick={()=>toggleLike(item.id)}><Heart size={18} fill={liked.includes(item.id)?'currentColor':'none'}/></button></div><div className="foodBody"><div className="foodTop"><h3>{item.name}</h3><b>{money(item.price)}</b></div><p>{item.desc}</p><div className="foodBottom"><span className="rating"><Star size={15} fill="currentColor"/> {item.rating}</span><button className="add" onClick={()=>add(item)}><Plus size={17}/> Add</button></div></div></article>)}</div>{!filtered.length&&<div className="empty">No dishes found. Try another search or category.</div>}</section>
   <section id="about" className="about section"><div className="aboutPics"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85"/><img src="https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=700&q=85"/><div className="since"><b>2014</b><span>serving joy</span></div></div><div className="aboutText"><span className="eyebrow">OUR STORY</span><h2>Food is our <em>love language.</em></h2><p>We started Bella Bites with one simple idea: a restaurant should feel like your favorite place to gather. Our kitchen blends timeless comfort food with modern twists, using ingredients sourced from local farmers whenever possible.</p><p>Every plate is cooked to order, every table is welcomed like family, and every visit should leave you with something worth remembering.</p><div className="features"><div><ChefHat/><b>Chef crafted</b><small>Every dish made fresh</small></div><div><Heart/><b>Made with love</b><small>Quality in every bite</small></div><div><CheckCircle/><b>100% fresh</b><small>Local ingredients</small></div></div></div></section>
   <section className="offer"><div><span className="eyebrow">WEEKEND SPECIAL</span><h2>Get 20% off your <em>first order.</em></h2><p>Use code <strong>BELLA20</strong> at checkout. Dine-in & takeaway.</p></div><button className="primary" onClick={()=>{setActive('All');scroll('menu')}}>Order Now <ArrowRight size={18}/></button></section>
   <section id="reviews" className="section reviews"><div className="centerHead"><span className="eyebrow">GUEST LOVE</span><h2>Don't just take our <em>word for it.</em></h2></div><div className="reviewGrid">{[['“','The truffle pizza is absolutely incredible. Beautiful atmosphere, super friendly staff and every bite was perfect.','Priya Sharma'],['“','Finally a place where vegetarian food gets the attention it deserves. The paneer platter was phenomenal!','Rahul Mehta'],['“','The perfect date-night spot. Great food, beautiful interiors and the chocolate lava cake is a must-have.','Ananya Singh']].map((r,i)=><div className="review" key={i}><div className="stars">★★★★★</div><p>{r[1]}</p><b>{r[2]}</b><small>Verified guest</small></div>)}</div></section>
   <section id="contact" className="contact section"><div><span className="eyebrow">COME SAY HELLO</span><h2>Let's make your next meal <em>special.</em></h2><p>Walk in, order online or reserve your favorite table. We can't wait to serve you.</p><div className="contactList"><div><MapPin/><span><b>Visit us</b>12 Food Street, Your City</span></div><div><Clock/><span><b>Opening hours</b>Mon–Sun · 11:00 AM–11:00 PM</span></div><div><Phone/><span><b>Call us</b>+91 98765 43210</span></div></div></div><form onSubmit={e=>{e.preventDefault();alert('Table request received! We will call you shortly.')}}><h3>Reserve a table</h3><input required placeholder="Your name"/><input required type="tel" placeholder="Phone number"/><div className="two"><input required type="date"/><input required type="time"/></div><select><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select><button className="primary">Book Table <ArrowRight size={18}/></button></form></section>
  </main>
  <footer><div className="logo">🍽 Bella<span className="accent">Bites</span></div><p>Good food. Great mood. Always.</p><div>© 2026 Bella Bites</div></footer>
  {cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="cart" onClick={e=>e.stopPropagation()}><div className="cartHead"><h2>Your Order <span>({count})</span></h2><button onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length?<><div className="cartItems">{cart.map(x=><div className="cartItem" key={x.id}><img src={x.img}/><div><b>{x.name}</b><small>{money(x.price)} each</small><div className="qty"><button onClick={()=>change(x.id,-1)}><Minus size={14}/></button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}><Plus size={14}/></button></div></div><strong>{money(x.price*x.qty)}</strong></div>)}</div><div className="cartFoot"><div><span>Subtotal</span><b>{money(total)}</b></div><small>Taxes and delivery calculated at checkout.</small><button className="primary full" onClick={()=>setCheckout(true)}>Checkout <ArrowRight size={18}/></button></div></>:<div className="emptyCart"><ShoppingBag size={48}/><h3>Your cart is empty</h3><p>Add something delicious from our menu.</p><button className="primary" onClick={()=>{setCartOpen(false);scroll('menu')}}>Browse Menu</button></div>}</aside></div>}
  {checkout&&<div className="modalOverlay"><div className="checkout"><button className="close" onClick={()=>setCheckout(false)}><X/></button>{ordered?<div className="success"><CheckCircle size={64}/><h2>Order confirmed!</h2><p>Thanks for ordering from Bella Bites. Your delicious food is on its way.</p><button className="primary" onClick={()=>{setOrdered(false);setCheckout(false);setCart([]);setCartOpen(false)}}>Done</button></div>:<><span className="eyebrow">CHECKOUT</span><h2>Almost <em>there.</em></h2><div className="orderTotal"><span>Order total</span><b>{money(total)}</b></div><form onSubmit={e=>{e.preventDefault();setOrdered(true)}}><input required placeholder="Full name"/><input required type="tel" placeholder="Phone number"/><input required placeholder="Delivery address"/><div className="two"><input required placeholder="City"/><input required placeholder="Pincode"/></div><button className="primary full">Place Order · {money(total)}</button></form></>}</div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
